-- Script was generated by Devart dbForge Studio Express for MySQL, Version 6.0.493.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 14/11/2013 11:42:57
-- Server version: 5.6.11
-- Client version: 4.1

SET NAMES 'utf8';
INSERT INTO es_pratica3.aluno(cpf, nome, nomeUsuario, email, dataNascimento, matricula, semestreIngresso, metodoIngresso, pontuacaoVestibular, situacao, pontuacao) VALUES
('010.325.689-02', 'Rofrigo Zanella', 'rzanella', 'rodrigo@exemplo.com', NULL, NULL, NULL, NULL, NULL, NULL, 500);
INSERT INTO es_pratica3.aluno(cpf, nome, nomeUsuario, email, dataNascimento, matricula, semestreIngresso, metodoIngresso, pontuacaoVestibular, situacao, pontuacao) VALUES
('025.180.450-56', 'Henrique Dambros', 'hdambros', 'hvdambros@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, 450);
INSERT INTO es_pratica3.aluno(cpf, nome, nomeUsuario, email, dataNascimento, matricula, semestreIngresso, metodoIngresso, pontuacaoVestibular, situacao, pontuacao) VALUES
('100.252.666-99', 'Paulo dos Santos', 'psantos', 'paulo@uol.com', NULL, NULL, NULL, NULL, NULL, NULL, 300);
INSERT INTO es_pratica3.disciplina(codigo, nome, ehEletiva, numCreditos) VALUES
('INF01023', 'Arquitetura e Desempenho de Banco de Dados', True, 4);
INSERT INTO es_pratica3.disciplina(codigo, nome, ehEletiva, numCreditos) VALUES
('INF01032', 'Empreendimento em InformÃ¡tica', False, 4);
INSERT INTO es_pratica3.disciplina(codigo, nome, ehEletiva, numCreditos) VALUES
('INF01120', 'TÃ©cnicas de ConstruÃ§Ã£o de Programas', False, 4);
INSERT INTO es_pratica3.disciplina(codigo, nome, ehEletiva, numCreditos) VALUES
('INF01124', 'ClassificaÃ§Ã£o e Pesquisa de Dados', False, 4);
INSERT INTO es_pratica3.disciplina(codigo, nome, ehEletiva, numCreditos) VALUES
('INF01142', 'Sistemas Operacionais I N', False, 4);
INSERT INTO es_pratica3.disciplina(codigo, nome, ehEletiva, numCreditos) VALUES
('INF01145', 'Fundamentos de Banco de Dados', False, 4);
INSERT INTO es_pratica3.disciplina(codigo, nome, ehEletiva, numCreditos) VALUES
('INF01147', 'Compiladores', False, 4);
INSERT INTO es_pratica3.disciplina(codigo, nome, ehEletiva, numCreditos) VALUES
('INF01209', 'Fundamentos de TolerÃ¢ncia a Falhas', False, 4);
INSERT INTO es_pratica3.disciplina(codigo, nome, ehEletiva, numCreditos) VALUES
('INF05516', 'SemÃ¢ntica Formal N', False, 4);
INSERT INTO es_pratica3.pre_requisito(codigoDisciplina, codigoDisciplinaRequisito) VALUES
('INF01023', 'INF01145');
INSERT INTO es_pratica3.pre_requisito(codigoDisciplina, codigoDisciplinaRequisito) VALUES
('INF01145', 'INF01124');
INSERT INTO es_pratica3.pre_requisito(codigoDisciplina, codigoDisciplinaRequisito) VALUES
('INF01147', 'INF05516');
INSERT INTO es_pratica3.pre_requisito(codigoDisciplina, codigoDisciplinaRequisito) VALUES
('INF01209', 'INF01142');
INSERT INTO es_pratica3.professor(cpf, nome, email, nomeUsuario, dataNascimento, areaInteresse) VALUES
('001.002.003-04', 'Marcelo Pimenta', 'mpimenta@inf.ufrgs.br', 'mpimenta', NULL, NULL);
INSERT INTO es_pratica3.professor(cpf, nome, email, nomeUsuario, dataNascimento, areaInteresse) VALUES
('003.669.876-26', 'Manuel Oliveira', 'moliveira@inf.ufrgs.br', 'moliveira', NULL, NULL);
INSERT INTO es_pratica3.professor(cpf, nome, email, nomeUsuario, dataNascimento, areaInteresse) VALUES
('025.301.254-56', 'Mariana Luderitz Kolberg', 'mlkolberg@inf.ufrgs.br', 'mlkolberg', NULL, NULL);
INSERT INTO es_pratica3.professor(cpf, nome, email, nomeUsuario, dataNascimento, areaInteresse) VALUES
('032.256.215-89', 'Taisy Silva Weber', 'tsweber@inf.ufrgs.br', 'tsweber', NULL, NULL);
INSERT INTO es_pratica3.professor(cpf, nome, email, nomeUsuario, dataNascimento, areaInteresse) VALUES
('123.456.789-10', 'SÃ©rgio Cechin', 'scechin@inf.ufrgs.br', 'scechin', NULL, NULL);
INSERT INTO es_pratica3.professor(cpf, nome, email, nomeUsuario, dataNascimento, areaInteresse) VALUES
('125.254.698-00', 'Lucas Schnorr', 'lschnorr@inf.ufrgs.br', 'lschnorr', NULL, NULL);
INSERT INTO es_pratica3.professor(cpf, nome, email, nomeUsuario, dataNascimento, areaInteresse) VALUES
('154.258.548-12', 'Cirano Iochpe', 'ciochpe@inf.ufrgs.br', 'cioshpe', NULL, NULL);
INSERT INTO es_pratica3.professor(cpf, nome, email, nomeUsuario, dataNascimento, areaInteresse) VALUES
('501.254.328-98', 'Luciana Porcher Nedel', 'lpnedel@inf.ufrgs.br', 'lpnedel', NULL, NULL);
INSERT INTO es_pratica3.sistema(estado, semestre) VALUES
('matricula', '2011/1');
INSERT INTO es_pratica3.turma(id, codigo, codigoDisciplina, horario, diasSemana, semestre, numvagas, cpfProfessor) VALUES
(1, 'A', 'INF01124', '10:30', NULL, '2013/2', 40, '003.669.876-26');
INSERT INTO es_pratica3.turma(id, codigo, codigoDisciplina, horario, diasSemana, semestre, numvagas, cpfProfessor) VALUES
(2, 'B', 'INF01124', '8:30', NULL, '2013/2', 25, '003.669.876-26');
INSERT INTO es_pratica3.turma(id, codigo, codigoDisciplina, horario, diasSemana, semestre, numvagas, cpfProfessor) VALUES
(3, 'A', 'INF01124', '13:30', NULL, '2013/1', 30, '003.669.876-26');
INSERT INTO es_pratica3.turma(id, codigo, codigoDisciplina, horario, diasSemana, semestre, numvagas, cpfProfessor) VALUES
(4, 'A', 'INF01124', '10:30', NULL, '2012/2', 30, '003.669.876-26');
INSERT INTO es_pratica3.turma(id, codigo, codigoDisciplina, horario, diasSemana, semestre, numvagas, cpfProfessor) VALUES
(5, 'A', 'INF01124', '13:30', NULL, '2012/1', 25, '003.669.876-26');
INSERT INTO es_pratica3.turma(id, codigo, codigoDisciplina, horario, diasSemana, semestre, numvagas, cpfProfessor) VALUES
(6, 'A', 'INF05516', '10:30', NULL, '2013/2', 25, '025.301.254-56');
INSERT INTO es_pratica3.turma(id, codigo, codigoDisciplina, horario, diasSemana, semestre, numvagas, cpfProfessor) VALUES
(7, 'B', 'INF05516', '8:30', NULL, '2013/2', 20, '025.301.254-56');
INSERT INTO es_pratica3.turma(id, codigo, codigoDisciplina, horario, diasSemana, semestre, numvagas, cpfProfessor) VALUES
(8, 'A', 'INF05516', '8:30', NULL, '2013/1', 20, '025.301.254-56');
INSERT INTO es_pratica3.turma(id, codigo, codigoDisciplina, horario, diasSemana, semestre, numvagas, cpfProfessor) VALUES
(9, 'B', 'INF05516', '13:30', NULL, '2013/1', 20, '025.301.254-56');
INSERT INTO es_pratica3.turma(id, codigo, codigoDisciplina, horario, diasSemana, semestre, numvagas, cpfProfessor) VALUES
(10, 'A', 'INF05516', '13:30', NULL, '2012/2', 20, '025.301.254-56');
INSERT INTO es_pratica3.turma(id, codigo, codigoDisciplina, horario, diasSemana, semestre, numvagas, cpfProfessor) VALUES
(11, 'A', 'INF05516', '10:30', NULL, '2012/1', 30, '025.301.254-56');
INSERT INTO es_pratica3.turma(id, codigo, codigoDisciplina, horario, diasSemana, semestre, numvagas, cpfProfessor) VALUES
(12, 'A', 'INF01209', '8:30', NULL, '2013/2', 15, '032.256.215-89');
INSERT INTO es_pratica3.turma(id, codigo, codigoDisciplina, horario, diasSemana, semestre, numvagas, cpfProfessor) VALUES
(13, 'C', 'INF01209', '15:30', NULL, '2013/2', 10, '032.256.215-89');
INSERT INTO es_pratica3.turma(id, codigo, codigoDisciplina, horario, diasSemana, semestre, numvagas, cpfProfessor) VALUES
(14, 'D', 'INF01209', '17:30', NULL, '2013/1', 5, '032.256.215-89');
INSERT INTO es_pratica3.turma(id, codigo, codigoDisciplina, horario, diasSemana, semestre, numvagas, cpfProfessor) VALUES
(15, 'B', 'INF01209', '10:30', NULL, '2012/2', 15, '032.256.215-89');
INSERT INTO es_pratica3.turma(id, codigo, codigoDisciplina, horario, diasSemana, semestre, numvagas, cpfProfessor) VALUES
(16, 'A', 'INF01209', '15:30', NULL, '2012/1', 5, '032.256.215-89');
INSERT INTO es_pratica3.turma(id, codigo, codigoDisciplina, horario, diasSemana, semestre, numvagas, cpfProfessor) VALUES
(17, 'E', 'INF01209', '19:30', NULL, '2011/2', 50, '032.256.215-89');
INSERT INTO es_pratica3.turma(id, codigo, codigoDisciplina, horario, diasSemana, semestre, numvagas, cpfProfessor) VALUES
(18, 'A', 'INF01147', '13:30', NULL, '2013/2', 20, '125.254.698-00');
INSERT INTO es_pratica3.turma(id, codigo, codigoDisciplina, horario, diasSemana, semestre, numvagas, cpfProfessor) VALUES
(19, 'D', 'INF01147', '10:30', NULL, '2013/2', 15, '125.254.698-00');
INSERT INTO es_pratica3.turma(id, codigo, codigoDisciplina, horario, diasSemana, semestre, numvagas, cpfProfessor) VALUES
(20, 'C', 'INF01147', '8:30', NULL, '2013/1', 20, '125.254.698-00');
INSERT INTO es_pratica3.turma(id, codigo, codigoDisciplina, horario, diasSemana, semestre, numvagas, cpfProfessor) VALUES
(21, 'B', 'INF01147', '10:30', NULL, '2013/1', 15, '125.254.698-00');
INSERT INTO es_pratica3.turma(id, codi